config/routes.rb
Rails.application.routes.draw do
  resources :curation_tags
  get 'user/show'

  root 'videos#index'
  resources :curation_likes
  resources :curation_comments
  resources :curation_videos
  resources :curations
  resources :video_tags
  resources :tags
  resources :video_likes
  resources :video_comments
  get 'videos/:id', to: 'videos#show', as: :video
  resources :videos
  devise_for :users
  get 'users/:id', to: 'users#show', as: :user
  resources :users do
    member do
     get :following, :followers
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :video
end

app/models/curation.rb
class Curation < ApplicationRecord
  belongs_to :user
  has_many :videos, :through => :curation_videos
  has_many :curation_videos
  has_many :curation_likes
  has_many :users, :through => :curation_likes
  has_many :curation_comments
  has_many :curation_tags  
end

app/models/curation_comment.rb
class CurationComment < ApplicationRecord
  belongs_to :curation
  belongs_to :user
end

app/models/curation_like.rb
class CurationLike < ApplicationRecord
  belongs_to :user
  belongs_to :curation
end

app/models/curation_tag.rb
class CurationTag < ApplicationRecord
  belongs_to :tag
  belongs_to :curation
end

app/models/curation_video.rb
class CurationVideo < ApplicationRecord
  belongs_to :curation
  belongs_to :video
end

app/models/popular.rb
class Popular < ApplicationRecord
  belongs_to :video
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"


end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :video_tags
  has_many :videos, :through => :video_tags
  has_many :curations, :through => :curation_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :video_comment
  has_many :videos
  has_one :video, :through => :video_comments
  has_many :video_likes
  has_one :video, :through => :video_likes
  has_many :curations
  has_many :curation_likes

  has_many :bookmarks
  has_many :videos, through: :bookmarks

  has_many :active_relationships, class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :active_relationships,class_name:  "Relationship", foreign_key: "following_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower


  has_many :passive_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy

    has_many :followers, through: :passive_relationships, source: :follower

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(following_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end


end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  has_many :video_tags
  has_many :videos
  has_many :tags, :through => :video_tag
  has_many :video_comments
  has_many :users, :through => :video_comments
  has_many :video_likes
  has_many :users, :through => :video_likes
  has_many :populars
  has_many :bookmarks
end

app/models/video_comment.rb
class VideoComment < ApplicationRecord
  belongs_to :video
  belongs_to :user
  has_many :videos
end

app/models/video_like.rb
class VideoLike < ApplicationRecord
  belongs_to :video
  belongs_to :user
  
end

app/models/video_tag.rb
class VideoTag < ApplicationRecord
  belongs_to :tag
  belongs_to :video
  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, :authenticate_user!, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    # @videos = Video.all
    @videos = Video.page(params[:page])
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @comment = Video.find(params[:id]).video_comments.new
    @videos = Video.all
    @video_comments = Video.find(params[:id]).video_comments.all
    @video_like = Video.find(params[:id]).video_likes.new
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }

      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:url, :title, :description, :website, :user_id, :thumbnails)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/curations_helper.rb
module CurationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_tags_helper.rb
module VideoTagsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(video) do |f| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :thumbnails %>
    <%= f.text_field :thumbnails %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/_popular_template.html.erb
<div class="row">
  <% @populars.each do |popular| %>
  <% video = popular.video %>
<p id="notice"><%= notice %></p>
  <div class="col-xs-6">
    <div class="thumbnail">
      <img src="holder.js/200x200" alt="...">
      <div class="caption">
        <p>お気に入り数：♡<%= video.video_likes.count%></p>

        <%= link_to video_path(video) do %>
          <strong><h3><%= video.title %></h3></strong>
        <% end %>

        <ul>
          <% video.video_tags.each do |tag| %>
            <li><%= tag.tag.tag %></li>
          <% end %>
        </ul>

        <div><p>動画リストに保存</p></div>
          <% video.video_comments.each do |comment| %>
            <div class="comment">
              <%= comment.user.username %>
              <%= comment.comment %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
  <% end %>
</div>
<%= link_to 'New Video', new_video_path %>

app/views/videos/_video.html.erb
<tr class="video">
    <td>
        <div class="thumbnail"><img src="holder.js/200x200" alt="...">
            <div class="caption">
                <%= link_to video_path(video) do %>
                    <strong><h3><%= video.title %></h3></strong>
                <% end %>
                <p>お気に入り数：♡<%= video.video_likes.count%></p>
                <ul>
                    <% video.video_tags.each do |tag| %>
                        <li><%= tag.tag.tag %></li>
                    <% end %>
                </ul>
                <p>動画リストに保存</p>
                <% video.video_comments.each do |comment| %>
                    <div class="comment">
                        <%= comment.user.username %>
                        <%= comment.comment %>
                    </div>
                <% end %>
            </div>
        </div>
    </td>
</tr>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<!-- <p id="notice"><%= notice %></p>
<div class="row">
  <% @videos.each do |video| %>
  <div class="col-xs-6">
    <div class="thumbnail">
      <img src="holder.js/200x200" alt="...">
      <div class="caption">
        <p>お気に入り数：♡<%= video.video_likes.count%></p>
        <%= link_to video_path(video) do %>
          <strong><h3><%= video.title %></h3></strong>
        <% end %>
        <ul>
          <% video.video_tags.each do |tag| %>
            <li><%= tag.tag.tag %></li>
          <% end %>
        </ul>
        <div><p>動画リストに保存</p></div>
          <% video.video_comments.each do |comment| %>
            <div class="comment">
              <%= comment.user.username %>
              <%= comment.comment %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
  <% end %>
</div>

<p><%= link_to 'New Video', new_video_path %></p>

<p><%= paginate @videos %></p> -->


<div class="row">
    <div class="col-xs-6">
        <table id="videos">
            <tbody class="page">
                <%= render @videos %>
            </tbody>
        </table>
    </div>
</div>


<br>

<%= link_to 'new Video', new_video_path %>

<!--一番下に追加 -->
<%= paginate @videos %>

app/views/videos/index.js.erb
$("#videos").append("<tbody class='page'><%= escape_javascript(render(@posts)) %></tbody>");

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/oneday_bookmark.html.erb
<% @bookmarks.each do |bookmark| %>
  <img src="<%= bookmark.video.thumbnails %>">
  <h1><%= bookmark.video.title %></h1>
  <% bookmark.video.video_tags.each do |video_tag| %>
      <span><%= video_tag.tag.tag %> |  </span>
  <% end %>
  <p><%= bookmark.video.description %></p>
  <p><%= button_to '1dayブックマーク', add_oneday_bookmark_path(bookmark.video) %></p>
  <p>お気に入り</p>
  <p>もっとみる</p>
<% end %>

app/views/videos/popular.html.erb
<%= render 'popular_template' %>

app/views/videos/popular_month.html.erb
<%= render 'popular_template' %>

app/views/videos/popular_today.html.erb
<%= render 'popular_template' %>

app/views/videos/popular_week.html.erb
<%= render 'popular_template' %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<!--   <iframe src="<%= @video.url %>" frameborder=0 width=510 height=400 scrolling=no allowfullscreen=allowfullscreen></iframe> -->
</p>

<p>
  <h3><strong>Title:</strong><%= @video.title %></h3>
</p>

<p>
  <% @video.video_tags.each do |tag| %>
    <li><%= tag.tag.tag %></li>
  <% end %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<p>
  <button type="button" class="btn btn-primary">1Dayブックマーク</button>
</p>

<%= form_for @video_like do |f| %>
  <%= f.hidden_field :video_id , :value => @video.id %>
  <%= f.hidden_field :user_id , :value => current_user.id %>
  <%= f.submit %>
<% end %>

<hr>
<div><p>コメント一覧</p></div>
  <% @video_comments.each do |video_comment| %>
    <p>USER<%= video_comment.user_id %>:　<%= video_comment.comment %></p>
  <% end %>
</div>

<hr>
<div><p>コメント欄</p></div>
  <%= form_for(@comment) do |f| %>
    <%= f.hidden_field :video_id , :value => @video.id %>
    <%= f.hidden_field :user_id , :value => current_user.id %>
    <%= f.text_field :comment %>
    <%= f.submit 'コメントを投稿する' %>
  <% end %>
</div>

<hr>
<div><p>関連動画表示</p></div>
<% @videos.first(10).each do | video | %>
  <div style="padding: 10px; margin-bottom: 10px; border: 1px dotted #333333; border-radius: 5px;">
    <p><strong>Title:</strong><%= video.title %></p>
    <p><strong>Description:</strong><%= @video.description %></p>
  </div>
<% end %>

<hr>
<%= link_to 'Edit', edit_video_path(@video) %> |