config/routes.rb
Rails.application.routes.draw do
  resources :curation_tags
  get 'user/show'

  root 'videos#index'
  resources :curation_likes
  resources :curation_comments
  resources :curation_videos
  resources :curations
  resources :video_tags
  resources :tags
  resources :video_likes
  resources :video_comments
  get 'videos/:id', to: 'videos#show', as: :video
  resources :videos
  devise_for :users
  get 'users/:id', to: 'users#show', as: :user
  resources :users do
    member do
     get :following, :followers
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :video
end

app/models/curation.rb
class Curation < ApplicationRecord
  belongs_to :user
  has_many :videos, :through => :curation_videos
  has_many :curation_videos
  has_many :curation_likes
  has_many :users, :through => :curation_likes
  has_many :curation_comments
  has_many :curation_tags  
end

app/models/curation_comment.rb
class CurationComment < ApplicationRecord
  belongs_to :curation
  belongs_to :user
end

app/models/curation_like.rb
class CurationLike < ApplicationRecord
  belongs_to :user
  belongs_to :curation
end

app/models/curation_tag.rb
class CurationTag < ApplicationRecord
  belongs_to :tag
  belongs_to :curation
end

app/models/curation_video.rb
class CurationVideo < ApplicationRecord
  belongs_to :curation
  belongs_to :video
end

app/models/popular.rb
class Popular < ApplicationRecord
  belongs_to :video
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"


end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :video_tags
  has_many :videos, :through => :video_tags
  has_many :curations, :through => :curation_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :video_comment
  has_many :videos
  has_one :video, :through => :video_comments
  has_many :video_likes
  has_one :video, :through => :video_likes
  has_many :curations
  has_many :curation_likes

  has_many :bookmarks
  has_many :videos, through: :bookmarks

  has_many :active_relationships, class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :active_relationships,class_name:  "Relationship", foreign_key: "following_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower


  has_many :passive_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy

    has_many :followers, through: :passive_relationships, source: :follower

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(following_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end


end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  has_many :video_tags
  has_many :videos
  has_many :tags, :through => :video_tag
  has_many :video_comments
  has_many :users, :through => :video_comments
  has_many :video_likes
  has_many :users, :through => :video_likes
  has_many :populars
  has_many :bookmarks
end

app/models/video_comment.rb
class VideoComment < ApplicationRecord
  belongs_to :video
  belongs_to :user
  has_many :videos
end

app/models/video_like.rb
class VideoLike < ApplicationRecord
  belongs_to :video
  belongs_to :user
  
end

app/models/video_tag.rb
class VideoTag < ApplicationRecord
  belongs_to :tag
  belongs_to :video
  
end

app/controllers/video_comments_controller.rb
class VideoCommentsController < ApplicationController
  before_action :set_video_comment, only: [:show, :edit, :update, :destroy]

  # GET /video_comments
  # GET /video_comments.json
  def index
    @video_comments = VideoComment.all
  end

  # GET /video_comments/1
  # GET /video_comments/1.json
  def show
  end

  # GET /video_comments/new
  def new
    @video_comment = VideoComment.new
  end

  # GET /video_comments/1/edit
  def edit
  end

  # POST /video_comments
  # POST /video_comments.json
  def create
    @video_comment = VideoComment.new(video_comment_params)

    respond_to do |format|
      if @video_comment.save
        format.html { redirect_to controller: 'videos', action: 'show', id: params[:video_comment][:video_id] }
      else
        format.html { render :new }
        format.json { render json: @video_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /video_comments/1
  # PATCH/PUT /video_comments/1.json
  def update
    respond_to do |format|
      if @video_comment.update(video_comment_params)
        format.html { redirect_to @video_comment, notice: 'Video comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @video_comment }
      else
        format.html { render :edit }
        format.json { render json: @video_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_comments/1
  # DELETE /video_comments/1.json
  def destroy
    @video_comment.destroy
    respond_to do |format|
      format.html { redirect_to video_comments_url, notice: 'Video comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_comment
      @video_comment = VideoComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_comment_params
      params.require(:video_comment).permit(:video_id, :user_id, :comment)
    end
end

app/helpers/curations_helper.rb
module CurationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_comments_helper.rb
module VideoCommentsHelper
end

app/helpers/video_tags_helper.rb
module VideoTagsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/video_comments/_form.html.erb
<%= form_for(video_comment) do |f| %>
  <% if video_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video_comment.errors.count, "error") %> prohibited this video_comment from being saved:</h2>

      <ul>
      <% video_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :video_id %>
    <%= f.text_field :video_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/video_comments/edit.html.erb
<h1>Editing Video Comment</h1>

<%= render 'form', video_comment: @video_comment %>

<%= link_to 'Show', @video_comment %> |
<%= link_to 'Back', video_comments_path %>

app/views/video_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Video Comments</h1>

<table>
  <thead>
    <tr>
      <th>Video</th>
      <th>User</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @video_comments.each do |video_comment| %>
      <tr>
        <td><%= video_comment.video %></td>
        <td><%= video_comment.user %></td>
        <td><%= video_comment.comment %></td>
        <td><%= link_to 'Show', video_comment %></td>
        <td><%= link_to 'Edit', edit_video_comment_path(video_comment) %></td>
        <td><%= link_to 'Destroy', video_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video Comment', new_video_comment_path %>

app/views/video_comments/new.html.erb
<h1>New Video Comment</h1>

<%= render 'form', video_comment: @video_comment %>

<%= link_to 'videos', videos_path %>

app/views/video_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Video:</strong>
  <%= @video_comment.video %>
</p>

<p>
  <strong>User:</strong>
  <%= @video_comment.user %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @video_comment.comment %>
</p>

<%= link_to 'Edit', edit_video_comment_path(@video_comment) %> |
<%= link_to 'Back', video_comments_path %>