config/routes.rb
Rails.application.routes.draw do
  resources :curation_tags
  get 'user/show'

  root 'videos#index'
  resources :curation_likes
  resources :curation_comments
  resources :curation_videos
  resources :curations
  resources :video_tags
  resources :tags
  resources :video_likes
  resources :video_comments
  get 'videos/:id', to: 'videos#show', as: :video
  resources :videos
  devise_for :users
  get 'users/:id', to: 'users#show', as: :user
  resources :users do
    member do
     get :following, :followers
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :video
end

app/models/curation.rb
class Curation < ApplicationRecord
  belongs_to :user
  has_many :videos, :through => :curation_videos
  has_many :curation_videos
  has_many :curation_likes
  has_many :users, :through => :curation_likes
  has_many :curation_comments
  has_many :curation_tags  
end

app/models/curation_comment.rb
class CurationComment < ApplicationRecord
  belongs_to :curation
  belongs_to :user
end

app/models/curation_like.rb
class CurationLike < ApplicationRecord
  belongs_to :user
  belongs_to :curation
end

app/models/curation_tag.rb
class CurationTag < ApplicationRecord
  belongs_to :tag
  belongs_to :curation
end

app/models/curation_video.rb
class CurationVideo < ApplicationRecord
  belongs_to :curation
  belongs_to :video
end

app/models/popular.rb
class Popular < ApplicationRecord
  belongs_to :video
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"


end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :video_tags
  has_many :videos, :through => :video_tags
  has_many :curations, :through => :curation_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :video_comment
  has_many :videos
  has_one :video, :through => :video_comments
  has_many :video_likes
  has_one :video, :through => :video_likes
  has_many :curations
  has_many :curation_likes

  has_many :bookmarks
  has_many :videos, through: :bookmarks

  has_many :active_relationships, class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :active_relationships,class_name:  "Relationship", foreign_key: "following_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower


  has_many :passive_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy

    has_many :followers, through: :passive_relationships, source: :follower

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(following_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end


end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  has_many :video_tags
  has_many :videos
  has_many :tags, :through => :video_tag
  has_many :video_comments
  has_many :users, :through => :video_comments
  has_many :video_likes
  has_many :users, :through => :video_likes
  has_many :populars
  has_many :bookmarks
end

app/models/video_comment.rb
class VideoComment < ApplicationRecord
  belongs_to :video
  belongs_to :user
  has_many :videos
end

app/models/video_like.rb
class VideoLike < ApplicationRecord
  belongs_to :video
  belongs_to :user
  
end

app/models/video_tag.rb
class VideoTag < ApplicationRecord
  belongs_to :tag
  belongs_to :video
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:tag)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/curations_helper.rb
module CurationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_tags_helper.rb
module VideoTagsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/tags/_form.html.erb
<%= form_for(tag) do |f| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tag %>
    <%= f.text_field :tag %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.tag %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>
<h1>タグ検索</h1>
<span>トップ > <%= @tag.tag %></span>
<div class="row">
  <% @tag.videos.each do |video| %>
  <div class="col-xs-6">
    <div class="thumbnail">
      <img src="holder.js/200x200" alt="...">
      <div class="caption">
        <p>お気に入り数：♡<%= video.video_likes.count%></p>

        <%= link_to video_path(video) do %>
          <strong><h3><%= video.title %></h3></strong>
        <% end %>

        <ul>
          <% video.video_tags.each do |tag| %>
            <li><%= tag.tag.tag %></li>
          <% end %>
        </ul>

        <div><p>動画リストに保存</p></div>
          <% video.video_comments.each do |comment| %>
            <div class="comment">
              <%= comment.user.username %>
              <%= comment.comment %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
  <% end %>
</div>
<%= link_to 'New Video', new_video_path %>